spring.application.name=fintech

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech_app
spring.datasource.username=core
spring.datasource.password=arie12345

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
